lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
encoding: UTF-8
future: true
jailed: false
gfm_quirks: paragraph_end
repository: mudge/mudge.github.com
url: https://mudge.name
title: Paul Mucur
description: The personal web site of consultant Technical/Engineering Lead Paul Mucur.
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Procfile
  - README.markdown
  - jest.config.js
  - node_modules
  - package.json
  - yarn.lock
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
