lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
encoding: UTF-8
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
repository: mudge/mudge.github.com
url: https://mudge.name
title: Paul Mucur
description: The personal web site of software development consultant Paul Mucur.
permalink: pretty
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
